package com.learningsat.demoapp.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBGeneratedUuid;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.io.Serializable;

@DynamoDBTable(tableName = "UserInfo")
public class UserInfo implements Serializable {
  private static final long serialVersionUID = 1L;
  
  @DynamoDBGeneratedUuid(DynamoDBAutoGenerateStrategy.CREATE)
  private String userId;
  
  @DynamoDBRangeKey
  private String metadata;
  
  @DynamoDBAttribute
  private String firstName;
  
  @DynamoDBAttribute
  private String lastName;
  
  @DynamoDBAttribute
  private String email;
  
  @DynamoDBAttribute
  private String dob;
  
  @DynamoDBHashKey(attributeName = "userId")
  @DynamoDBAutoGeneratedKey
  public String getUserId() {
    return this.userId;
  }
  
  public void setUserId(String userId) {
    this.userId = userId;
  }
  
  public String getMetadata() {
    return this.metadata;
  }
  
  public void setMetadata(String metadata) {
    this.metadata = metadata;
  }
  
  public String getFirstName() {
    return this.firstName;
  }
  
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }
  
  public String getLastName() {
    return this.lastName;
  }
  
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }
  
  public String getEmail() {
    return this.email;
  }
  
  public void setEmail(String email) {
    this.email = email;
  }
  
  public String getDob() {
    return this.dob;
  }
  
  public void setDob(String dob) {
    this.dob = dob;
  }
}
